theme: jekyll-theme-minimal
title: Projeto IntegraMec
description: Visualização em Realidade Virtual do Potencial de interdiscipinaridade do curso de Engenharia Mecânica da Universidade Federal do Ceará!
